# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutual_tls_auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mutual_tls_auth.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15mutual_tls_auth.proto\"O\n\tLoanPoint\x12\x0c\n\x04rate\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x11\n\trange_min\x18\x03 \x01(\x05\x12\x11\n\trange_max\x18\x04 \x01(\x05\"A\n\x06Orders\x12\x1a\n\x06offers\x18\x01 \x03(\x0b\x32\n.LoanPoint\x12\x1b\n\x07\x64\x65mands\x18\x02 \x03(\x0b\x32\n.LoanPoint\"\x18\n\x08\x43urrency\x12\x0c\n\x04name\x18\x01 \x01(\t2.\n\x07Gateway\x12#\n\x0bloan_orders\x12\t.Currency\x1a\x07.Orders\"\x00\x62\x06proto3')
)




_LOANPOINT = _descriptor.Descriptor(
  name='LoanPoint',
  full_name='LoanPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate', full_name='LoanPoint.rate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='LoanPoint.amount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_min', full_name='LoanPoint.range_min', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range_max', full_name='LoanPoint.range_max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=104,
)


_ORDERS = _descriptor.Descriptor(
  name='Orders',
  full_name='Orders',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offers', full_name='Orders.offers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demands', full_name='Orders.demands', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=171,
)


_CURRENCY = _descriptor.Descriptor(
  name='Currency',
  full_name='Currency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Currency.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=197,
)

_ORDERS.fields_by_name['offers'].message_type = _LOANPOINT
_ORDERS.fields_by_name['demands'].message_type = _LOANPOINT
DESCRIPTOR.message_types_by_name['LoanPoint'] = _LOANPOINT
DESCRIPTOR.message_types_by_name['Orders'] = _ORDERS
DESCRIPTOR.message_types_by_name['Currency'] = _CURRENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoanPoint = _reflection.GeneratedProtocolMessageType('LoanPoint', (_message.Message,), dict(
  DESCRIPTOR = _LOANPOINT,
  __module__ = 'mutual_tls_auth_pb2'
  # @@protoc_insertion_point(class_scope:LoanPoint)
  ))
_sym_db.RegisterMessage(LoanPoint)

Orders = _reflection.GeneratedProtocolMessageType('Orders', (_message.Message,), dict(
  DESCRIPTOR = _ORDERS,
  __module__ = 'mutual_tls_auth_pb2'
  # @@protoc_insertion_point(class_scope:Orders)
  ))
_sym_db.RegisterMessage(Orders)

Currency = _reflection.GeneratedProtocolMessageType('Currency', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCY,
  __module__ = 'mutual_tls_auth_pb2'
  # @@protoc_insertion_point(class_scope:Currency)
  ))
_sym_db.RegisterMessage(Currency)



_GATEWAY = _descriptor.ServiceDescriptor(
  name='Gateway',
  full_name='Gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=199,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='loan_orders',
    full_name='Gateway.loan_orders',
    index=0,
    containing_service=None,
    input_type=_CURRENCY,
    output_type=_ORDERS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GATEWAY)

DESCRIPTOR.services_by_name['Gateway'] = _GATEWAY

# @@protoc_insertion_point(module_scope)
