# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mutual_tls_auth_pb2 as mutual__tls__auth__pb2


class GatewayStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.loan_orders = channel.unary_unary(
        '/Gateway/loan_orders',
        request_serializer=mutual__tls__auth__pb2.Currency.SerializeToString,
        response_deserializer=mutual__tls__auth__pb2.Orders.FromString,
        )


class GatewayServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def loan_orders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'loan_orders': grpc.unary_unary_rpc_method_handler(
          servicer.loan_orders,
          request_deserializer=mutual__tls__auth__pb2.Currency.FromString,
          response_serializer=mutual__tls__auth__pb2.Orders.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Gateway', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
